#!/usr/bin/with-contenv sh

mkdir /var/run/sshd
chmod 0755 /var/run/sshd

chmod 600 /home/gluster/.ssh/id_rsa
chmod 600 /home/gluster/.ssh/authorized_keys
chown gluster:gluster /home/gluster/.ssh/id_rsa /home/gluster/.ssh/authorized_keys

exec /usr/sbin/sshd -D \
    -o PermitTTY=no \
    -o AllowUsers=gluster \
    -o AuthenticationMethods=publickey \
    -o AuthorizedKeysFile=/home/gluster/.ssh/authorized_keys \
    -o PasswordAuthentication=no \
    -o PermitRootLogin=no
