#!/usr/bin/with-contenv sh

s6-svwait -u /etc/services.d/gluster

# get all services ip
# ssh to one of them and probe for peer

IP="$(getent hosts $HOSTNAME | awk '{ print $1 }')"
REPLICA=3 # will count from services
VOLUME=www
VOLUMEDIR="/volume/`hostname`/$VOLUME"


#ssh $NODE sh -c "

#"

mkdir -p $VOLUMEDIR

gluster peer probe $IP
gluster volume add-brick $VOLUME replica $REPLICA $IP:$VOLUMEDIR

exit 0
