#!/usr/bin/with-contenv sh

s6-svwait -u /etc/services.d/gluster

# get all services ip
# ssh to one of them and probe for peer

SERVICE=gluster
VOLUME=www

# warning, container should be run in swarm mode only
IP1="$(cat /etc/hosts | grep $HOSTNAME | awk '{ print $1 }' | sed -n 1p)"
IP2="$(cat /etc/hosts | grep $HOSTNAME | awk '{ print $1 }' | sed -n 2p)"
CLUSTER_NODES="$(dig +short tasks.$SERVICE | sed "/$IP1/d")"
VOLUMEDIR="/volume/$HOSTNAME/$VOLUME"

# --------------------------------------------------------

# @TODO: need to check if this node is already in cluster, if not, then join node to the cluster

# --------------------------------------------------------

# create volume dir if neccessary
mkdir -p $VOLUMEDIR

# empty cluster, initialize volume
if [[ "$CLUSTER_NODES" == "" ]]; then
    gluster volume create $VOLUME $IP1:$VOLUMEDIR force
else
    # total number of tasks in service
    REPLICA="$(expr $(echo $CLUSTER_NODES | wc -l) + 1)"

    # always use first node as cluster manager, wait 'till it boot up
    PRIMARY="$(echo $CLUSTER_NODES | sed -n 1p)"


    # add this node to cluster
    ssh -o StrictHostKeyChecking=no gluster@$PRIMARY sh -c "gluster peer probe $IP && gluster volume add-brick $VOLUME replica $REPLICA $IP1:$VOLUMEDIR force"
fi


exit 0
